
services:

  #########
  # LLMS
  #########
  llama3.2:
    provider:
      type: model
      options:
        model: ai/llama3.2

  qwen3:
    provider:
      type: model
      options:
        model: jimclark106/qwen3:4b-F16

  #########
  # MCPS
  ########
  # the mcp-gateway surfaces a restricted view of the tools
  # exposed by the MCP Toolkit
  # access gateway using SSE over http://mcp-gateway:9011/sse/...
  mcp-gateway:
    image: docker/agents_gateway:v2
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./docker-mcp.yaml:/app/docker-mcp.yaml"
      - "./config.yaml:/app/config.yaml"
    command:
      - --verbose
      - --transport=sse
      - --catalog=/app/docker-mcp.yaml
      - --config=/app/config.yaml
      - --secrets=docker-desktop:/run/secrets/mcp_secret
      - --servers=brave
      - --servers=resend
      - --servers=wikipedia-mcp
      - --tools=brave_web_search
      - --tools=get_article
      - --tools=get_summary
      - --tools=get_related_topics
      - --tools=send-email
      - --port=9011
    secrets:
      - mcp_secret

  # chat-store DB gives our app simple persistence for 
  # storing history of messages and threads
  chat-store:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=slim
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=chatstore
    volumes:
      - chat_store:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U slim -d chatstore"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  initialize-chat-store-schema:
    image: jimclark106/initialize-chat-store-schema
    build:
      context: .
      dockerfile: Dockerfile.initialize-chat-store-schema
    environment:
      - DATABASE_URL=postgresql://slim:pass@chat-store:5432/chatstore
    depends_on:
      chat-store:
        condition: service_healthy

  ##########
  # AGENT UI
  ##########
  mcp-ui:
    image: jimclark106/mcp-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://slim:pass@chat-store:5432/chatstore
      - MCP_GATEWAY_URL=http://mcp-gateway:9011/sse
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - llama3.2
      - qwen3
      - mcp-gateway
      - chat-store
      - initialize-chat-store-schema

volumes:
  chat_store:
  docker-prompts:
    name: docker-prompts

secrets:
  mcp_secret:
    file: ./.mcp.env
